# ============================================================
# Splunk Universal Forwarder — outputs.conf
# SOC Automation Lab 2.0 | Chinemelum Osholake
# Place at: C:\Program Files\SplunkUniversalForwarder\etc\system\local\outputs.conf
# Update server IP to match your Splunk VM IP
# ============================================================

[tcpout]
defaultGroup = default-autolb-group

[tcpout:default-autolb-group]
server = 10.0.2.15:9997

[tcpout-server://10.0.2.15:9997]
